{% set name = "boto3-stubs" %}
{% set version = "1.17.77" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/boto3-stubs-{{ version }}.tar.gz
  sha256: ab0acf8ac9534e097cb33b4c7a15cc3d211c34d3c4b861b89e3962680c613665

build:
  number: 1
  noarch: python
requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

outputs:
  - name: boto3-stubs
    requirements:
      run:
        - boto3
        - typing_extensions
    build:
      noarch: python
      script:
        - python -m pip install . -vv
    test:
      script: run_test.py
      commands:
        - pip check
      requires:
        - pip


  - name: boto3-stubs-essential
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
        - mypy_boto3_cloudformation={{ version }}
        - mypy_boto3_dynamodb={{ version }}
        - mypy_boto3_ec2={{ version }}
        - mypy_boto3_lambda={{ version }}
        - mypy_boto3_rds={{ version }}
        - mypy-boto3-s3={{ version }}
        - mypy_boto3_sqs={{ version }}
    test:
      script: test_essential.py
      imports:
        - mypy_boto3_cloudformation
        - mypy_boto3_dynamodb
        - mypy_boto3_ec2
        - mypy_boto3_lambda
        - mypy_boto3_rds
        - mypy_boto3_s3
        - mypy_boto3_sqs
      commands:
        - pip check
      requires:
        - pip
        - mypy_boto3_builder

about:
  home: https://github.com/vemel/mypy_boto3_builder
  summary: Type annotations for boto3 1.17.54, generated by mypy-boto3-buider 4.6.0
  dev_url: https://github.com/vemel/mypy_boto3_builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - thewchan
    - vemel
